### ISSUE TITLE
IE 64/no Flash, module don't work: No 'choose files button or link'

### ISSUE THREAD

**Issue by elz64** [Mark-H/EvoGallery#12]
Hi,
In W7/64, there's no Flash support (!) so the upload files management is not displayed.
An alternative for another way of dealing with files transfer should be a VERY good idea...

Thank you

**Comment by noizo** [comment]
Best option would be using plupload library instead of dying flash plugin.
Hope someone is looking into it.

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
