### ISSUE TITLE
Option to order the gallery view trough backend sort order

### ISSUE THREAD

**Issue by mdehaan** [Mark-H/EvoGallery#15]
It would be very nice to have an option to order the gallies display mode by the backend sort order gallerySortBy=`sortorder`. It would be great if it would be handled the same way as wayfinder does with containers and such..

The ideal solution would be to have a separate admin section to sort the galleries by drag and drop just like the modx docmanager can. The reason why I do prefer this method over the modx document tree is because I like to organize all my photoalbums with containers trough the document tree because I have so many. And I use the container structure to generate the navigation with wayfinder. 

I understand that the second option requires a lot more work, but it will be worth it :)

For any questions just send me a message. 
I will make a functional design for it if you require it.

Thanx in advance!

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
