### ISSUE TITLE
(improvement) Link URL field within upload / edit form

### ISSUE THREAD

**Issue by LeePorte** [Mark-H/EvoGallery#26]
Hi,

Would it be possible to add a URL field to upload / edit image template?

Looking through the code it looks to be an addition to the management.class.inc.php, the image_edit.html.tpl as well as a tweak to the display template to replace <a href="[+images_dir+][+filename+]"> with the new template variable to accommodate.

If I'm on the right lines I'm happy to help out with implementing this, If not feel free to give me a nudge in the correct direction.

Thanks

Lee

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
