### ISSUE TITLE
update bug if put EvoGallery to install

### ISSUE THREAD

**Issue by dmi3yy** [Mark-H/EvoGallery#39]
Ещё 1 баг нашел при обновлении  если модуль ставить сразу с modx 
тоесть запихнуть в папку install/assets/module получаем ошибку mysql 

<b>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'w': 940, 'h': 940, 'q': 95} &phpthumbThumb=PHPThumb config for thumbs in JSON;te' at line 1</b>

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
