### ISSUE TITLE
Random filenames are not dynamic

### ISSUE THREAD

**Issue by labasus** [Mark-H/EvoGallery#42]
I don't know is a bug or limited functionality, but let you know.

If module had "Random filenames" setting - NO, so you can upload some photos with original file names.
Then after you will change this setting to YES, all new photos will apply this (random filenames as aspected), but all the old photos - will be within original file names and "Regenerate all images" doesn't fix this.

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
