### ISSUE TITLE
Evogallery upload stops working when placed in root directory

### ISSUE THREAD

**Issue by witq** [Mark-H/EvoGallery#44]
Hi,

I'm having a strange issue with EvoGallery. It worked flawlessly on my development server where it was in a subfolder:

MODX_BASE_PATH      /volume1/web/projekty/fine-design/
MODX_BASE_URL       /projekty/fine-design/

I then moved it to the production server where it is places in absolute root:

MODX_BASE_PATH      /
MODX_BASE_URL       /

The images that were uploaded prior to the move appear fine. But when I try to upload new pictures they upload and get stuck at 100% and nothing happens. I checked, and the pictures get uploaded (they appear in the originals folder) but don't get processed.

I then moved the site to a subfolder like that:

MODX_BASE_PATH      /nowa/
MODX_BASE_URL       /nowa/

And EvoGallery started working fine.

Do you have any idea what may be wrong? Please do :)

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
