### ISSUE TITLE
- HTTP Error when files are uploaded

### ISSUE THREAD

**Issue by dnadave1986** [Mark-H/EvoGallery#46]
Hi There, 

I'm Dave from The Netherlands, new to modx, and I just installed de evogallery.
Followed all the installation steps, got no errors. Folder permissions for the galleries folder set to 777, and another gallery snipped that used the same folder worked fine.

the problem is that when I try to upload a file thru modules > evogallery , that I instantly get a http error.
since there are no other clues or problem numbers that appear, I don't know how to solve this issue.

do you guys know how to solve this issue ?

Greetings,

Dave

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
