### ISSUE TITLE
Images not uploading to filesystem

### ISSUE THREAD

**Issue by pwalsh** [Mark-H/EvoGallery#47]
I recently upgraded to MODX 1.0.6, and EvoGallery 1.1 beta 1.

I thought everything was working fine - existing galleries all work fine.

By now, when I try to add new images via EvoGallery, I select file and then upload file, I get no warnings in console, but the image itself does not gat saved to the filesystem.

A new instance is created in the DB, pointing to the "new" url, but there is no image there so it returns a 404.

I tested the native MODX Evolution file upload, and it works with no problems.

php has write permissions on galleries and all children.

I am running php-fpm behind nginx.

Any ideas?

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
