### ISSUE TITLE
Remake parameters in galleries display mode

### ISSUE THREAD

**Issue by evd** [Mark-H/EvoGallery#49]
Add parameters:
&parents - comma separated list of parents document's id which display to gallery, or \* for all documents, or empty if documents specify only by &includeDocsId parameter
&includeDocsId (or maybe &docsId) - comma separated list of document's id which display to gallery
&excludeDocsId - comma separated list of document's id which prevent display to gallery

Make parameters &docId and &excludeDocs deprecated

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
