### ISSUE TITLE
PHPThumb config personalization

### ISSUE THREAD

**Issue by labasus** [Mark-H/EvoGallery#51]
Is is possible to have different settings of PHPThumb config for some Folders or even documents?

For this moment we have only one PHPThumb config in the module config, this settings can be like Global one's.
Personal settings can be in Actions (Действия).

What for ....?
If we need to have a different sizes of  thumbs in some Folders or documents.

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
