### ISSUE TITLE
Display Single sortBy not Worked

### ISSUE THREAD

**Issue by gusdecool** [Mark-H/EvoGallery#52]
[!EvoGallery? &display=`single` &itemTpl=`evogallery` &sortBy=`id` &sortDir=`ASC` !]

Using that snippet, the sortBy not worked. Have tried sortDir ASC and DESC. nothing changes.

PS: 
I using EvoGallery 1.1.0-beta

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
