### ISSUE TITLE
No "Select Files" button in FireFox - solved

### ISSUE THREAD

**Issue by skorovin** [Mark-H/EvoGallery#54]
Hello!

MODx 1.0.6 + EvoGallery 1.1 Beta 1

The "Select Files" button is not displayed in FireFox 17.0 (in all other browsers it works fine).

What could be a reason of the problem?

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
