### ISSUE TITLE
Is there a way to use with YAMS Multi language?

### ISSUE THREAD

**Issue by fourroses666** [Mark-H/EvoGallery#60]
Is it possible to set the image title and description fields into 2 different languages?

somehow I need it to work with YAMS. 

maybe it is possible to add custom input formfields on backend?

like tv_en and tv_nl ?

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
