### ISSUE TITLE
Missing 'Save Order' Button

### ISSUE THREAD

**Issue by bartholomej** [Mark-H/EvoGallery#65]
We can reorder the images simply by dragging and dropping but there is no 'Save Order' Button anymore.

Latest evogallery + mm_widget_evogallery settings + MODx 1.0.12 (clear install)

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
