### ISSUE TITLE
Multiple Gallery id calls sorting

### ISSUE THREAD

**Issue by fruitwerks** [Mark-H/EvoGallery#9]
The sorting when using multiple galleries in one call appears to be very wrong.

Minimal expectant behavior should be per-id:sortorder, show id's in order called. 

Possibly add random support

**Comment by Mark-H** [comment]
EvoGallery is no longer supported here. [Please reopen the issue on the new repository if it's still valid.](https://github.com/extras-evolution/EvoGallery)
